DROP TABLE GlobalPolicy IF EXISTS;
CREATE TABLE GlobalPolicy (
  id varchar(5) NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (id)
);



DROP TABLE LightPathAlarmDetails IF EXISTS;
CREATE TABLE LightPathAlarmDetails (
  id varchar(255) NOT NULL,
  neid varchar(25) DEFAULT NULL,
  time bigint NOT NULL,
  duration bigint NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE LightPathAlarmSummaries IF EXISTS;
CREATE TABLE LightPathAlarmSummaries (
  pk bigint GENERATED BY DEFAULT AS IDENTITY (start with 1),
  id varchar(255) NOT NULL,
  severity varchar(5) NOT NULL,
  occurredTime bigint NOT NULL,
  serviceId varchar(28) NOT NULL,
  source varchar(25) NOT NULL,
  PRIMARY KEY (pk)
);

DROP TABLE LightPathEdge IF EXISTS;
CREATE TABLE LightPathEdge (
  pk bigint GENERATED BY DEFAULT AS IDENTITY (start with 1),
  id varchar(28) DEFAULT NULL,
  source varchar(25) NOT NULL,
  sourceAid varchar(28) NOT NULL,
  sourceChannel integer NOT NULL,
  target varchar(25) NOT NULL,
  targetAid varchar(28) NOT NULL,
  targetChannel integer NOT NULL,
  rate varchar(8) NOT NULL,
  CCT varchar(28) DEFAULT NULL,
  SWMATE varchar(28) DEFAULT NULL,
  mep varchar(255) NOT NULL,
  vlanId varchar(255) DEFAULT NULL,
  PRIMARY KEY (pk)
);

DROP TABLE LightPath IF EXISTS;
CREATE TABLE LightPath (
  serviceId varchar(28) NOT NULL,
  id varchar(28) NOT NULL,
  scheduleId varchar(28) NOT NULL,
  activationType varchar(255) NOT NULL,
  controllerId varchar(255) NOT NULL,
  scheduleName varchar(255) NOT NULL,
  status varchar(4) NOT NULL,
  vcat varchar(255) DEFAULT NULL,
  startTime bigint NOT NULL,
  endTime bigint NOT NULL,
  user varchar(255) NOT NULL,
  billingGroup varchar(255) NOT NULL,
  priority varchar(3) NOT NULL,
  mbs integer NOT NULL,
  rate varchar(8) NOT NULL,
  aEnd varchar(25) NOT NULL,
  zEnd varchar(25) NOT NULL,
  lp_1plus1_path_data varbinary(16777215),
  xml varchar(5000) NOT NULL,
  PRIMARY KEY (serviceId)
);

DROP TABLE NetworkElementAdjacency IF EXISTS;
CREATE TABLE NetworkElementAdjacency (
  pk varchar(255) NOT NULL,
  neid varchar(255) NOT NULL,
  port varchar(255) NOT NULL,
  txtag varchar(255) NOT NULL,
  rxtag varchar(255) NOT NULL,
  type varchar(255) NOT NULL,
  manualProvision boolean NOT NULL,
  PRIMARY KEY (pk)
);

DROP TABLE NetworkElementConnection IF EXISTS;
CREATE TABLE NetworkElementConnection (
  pk varchar(255) NOT NULL,
  id varchar(64) NOT NULL,
  data varbinary(16777215) NOT NULL,
  PRIMARY KEY (pk)
);

DROP TABLE NetworkElementFacility IF EXISTS;
CREATE TABLE NetworkElementFacility (
  pk varchar(64) NOT NULL,
  layer varchar(8) NOT NULL,
  shelf varchar(16) NOT NULL,
  slot varchar(16) NOT NULL,
  port varchar(16) NOT NULL,
  primaryState varchar(16) NOT NULL,
  signalingType varchar(16) NOT NULL,
  tna varchar(64) NOT NULL,
  siteId varchar(255) NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (pk)
);

DROP TABLE NetworkElement IF EXISTS;
CREATE TABLE NetworkElement (
  pk varchar(255),
  autoReDiscover boolean NOT NULL,
  commProtocol varchar(255) NOT NULL,
  id varchar(255) NOT NULL,
  managedBy varchar(255) NOT NULL,
  mode varchar(255) NOT NULL,
  neIndex integer NOT NULL,
  password varchar(255) NOT NULL,
  status varchar(255) NOT NULL,
  tid varchar(255) NOT NULL,
  type varchar(255) NOT NULL,
  userId varchar(255) NOT NULL,
  subType varchar(255) NOT NULL DEFAULT 'Unknown',
  neRelease varchar(255) NOT NULL,
  positionX double,
  positionY double,
  PRIMARY KEY (pk)
);

DROP TABLE ResourceGroups IF EXISTS;
CREATE TABLE ResourceGroups (
  groupId varchar(255) NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (groupId)
);


DROP TABLE Schedule IF EXISTS;
CREATE TABLE Schedule (
  id varchar(255) NOT NULL,
  activationType varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  status varchar(255) NOT NULL,
  startTime bigint NOT NULL,
  endTime bigint NOT NULL,
  duration bigint NOT NULL,
  userId varchar(255) NOT NULL,
  sourceEndpointUserGroup varchar(255) NOT NULL,
  targetEndpointUserGroup varchar(255) NOT NULL,
  billingGroup varchar(255) NOT NULL,
  sourceEndpointResourceGroup varchar(255) NOT NULL,
  targetEndpointResourceGroup varchar(255) NOT NULL,
  email varchar(255) NOT NULL,
  recurrenceType varchar(255) NOT NULL,
  recurrenceDay integer NOT NULL,
  recurrenceMonth integer NOT NULL,
  recurrenceWeekday varchar(255) NOT NULL,
  path_source varchar(255) NOT NULL,
  path_target varchar(255) NOT NULL,
  path_rate integer NOT NULL,
  path_srlg varchar(255) NOT NULL,
  path_cost integer NOT NULL,
  path_metric integer NOT NULL,
  path_hop integer NOT NULL,
  path_vcatRoutingOption varchar(255) NOT NULL,
  path_sharedriskservicegroup varchar(255) NOT NULL,
  path_protection varchar(255) NOT NULL,
  path_NameStringValue varchar(5000) NOT NULL,
  path_sourceendpoint_channel integer NOT NULL,
  path_sourceendpoint_id varchar(255) NOT NULL,
  path_sourceendpoint_tna varchar(255) NOT NULL,
  path_sourceendpoint_vlanid varchar(255) NOT NULL,
  path_targetendpoint_channel integer NOT NULL,
  path_targetendpoint_id varchar(255) NOT NULL,
  path_targetendpoint_tna varchar(255) NOT NULL,
  path_targetendpoint_vlanid varchar(255) NOT NULL,
  PRIMARY KEY (id)
--  ,
--  KEY startTime (startTime),
--  KEY endTime (endTime),
--  KEY duration (duration),
--  KEY billingGroup (billingGroup)
);

DROP TABLE Sites IF EXISTS;
CREATE TABLE Sites (
  id varchar(255) NOT NULL,
  location varchar(255) NOT NULL,
  description varchar(65000) NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE UserGroups IF EXISTS;
CREATE TABLE UserGroups (
  groupId varchar(255) NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (groupId)
);

DROP TABLE UserPreferences IF EXISTS;
CREATE TABLE UserPreferences (
  userId varchar(255) NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (userId)
);

DROP TABLE Users IF EXISTS;
CREATE TABLE Users (
  userId varchar(255) NOT NULL,
  xml varchar(65000) NOT NULL,
  PRIMARY KEY (userId)
);


DROP TABLE dracschema IF EXISTS;
create table dracschema (
    version int NOT NULL unique
);

DROP TABLE inbox IF EXISTS;
CREATE TABLE inbox (
  id integer GENERATED BY DEFAULT AS IDENTITY (start with 1),
  userId varchar(255) NOT NULL,
  date bigint NOT NULL,
  sender varchar(255) NOT NULL,
  receipient varchar(255) NOT NULL,
  cc varchar(255) DEFAULT NULL,
  unread varchar(10) DEFAULT NULL,
  replied varchar(10) DEFAULT NULL,
  deleted varchar(10) DEFAULT NULL,
  subject varchar(255) DEFAULT NULL,
  message varchar(65000),
  PRIMARY KEY (id)
);

DROP TABLE logs IF EXISTS;
CREATE TABLE logs (
  id integer GENERATED BY DEFAULT AS IDENTITY (start with 1),
  time bigint NOT NULL,
  originator varchar(255) NOT NULL,
  address varchar(255) NOT NULL,
  billingGroup varchar(255) NOT NULL,
  severity varchar(25) NOT NULL,
  category varchar(25) NOT NULL,
  logType varchar(25) NOT NULL,
  resource varchar(255) NOT NULL,
  result varchar(25) NOT NULL,
  descr varchar(255) NOT NULL,
  xml longtext NOT NULL,
  PRIMARY KEY (id)
);

DROP TABLE outbox IF EXISTS;
CREATE TABLE outbox (
  id integer GENERATED BY DEFAULT AS IDENTITY (start with 1),
  userId varchar(255) NOT NULL,
  date bigint NOT NULL,
  receipient varchar(255) NOT NULL,
  cc varchar(255) DEFAULT NULL,
  bcc varchar(255) DEFAULT NULL,
  deleted varchar(10) DEFAULT NULL,
  subject varchar(255) DEFAULT NULL,
  message varchar(65000),
  PRIMARY KEY (id)
);





