/**
 * <pre>
 * The owner of the original code is Ciena Corporation.
 *
 * Portions created by the original owner are Copyright (C) 2004-2010
 * the original owner. All Rights Reserved.
 *
 * Portions created by other contributors are Copyright (C) the contributor.
 * All Rights Reserved.
 *
 * Contributor(s):
 *   (Contributors insert name & email here)
 *
 * This file is part of DRAC (Dynamic Resource Allocation Controller).
 *
 * DRAC is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * DRAC is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
 * Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * </pre>
 */

/* Generated By:JavaCC: Do not edit this line. Gentl1StubConstants.java */
package genstub;

public interface Gentl1StubConstants {

	int EOF = 0;
	int ID = 5;
	int SPC = 6;
	int SEP = 7;
	int TERMINATOR = 8;
	int BLKSEP = 9;
	int COMMA = 10;
	int EMPTY = 11;
	int EQUAL = 12;
	int LSBRACE = 13;
	int RSBRACE = 14;
	int LABRACE = 15;
	int RABRACE = 16;
	int CMD = 17;
	int TL1WRAPPER = 18;
	int NE = 19;
	int VERSION = 20;
	int NUMBER = 21;
	int DATA = 22;
	int DESCRIPTION = 23;
	int RESP = 24;
	int EMBED = 25;
	int CLBRACE = 26;
	int CRBRACE = 27;
	int LP = 28;
	int RP = 29;
	int COMMENTSTART = 30;
	int COMMENTEND = 31;
	int BLOCKSEP = 32;
	int UNPRNTABLE = 33;

	int DEFAULT = 0;

	String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"",
	    "<ID>", "<SPC>", "\"-\"", "\";\"", "\":\"", "\",\"", "\"\"", "\"=\"",
	    "\"[\"", "\"]\"", "\"<\"", "\">\"", "\"#CMD\"", "\"#TL1WRAPPER\"",
	    "\"#NETYPE\"", "\"#VERSION\"", "\"#TOTALCOMMANDSNUMBER\"",
	    "\"#LASTMODIFIEDDATA\"", "\"#DESCRIPTION\"", "\"#RESP\"",
	    "\"#EMBEDDED\"", "\"{\"", "\"}\"", "\"(\"", "\")\"", "\"#COMMENTSTART\"",
	    "\"#COMMENTEND\"", "\"#BLOCKSEP\"", "\"#UNPRNTABLE\"", };

}
